spring:
  datasource:
    password: ALcoder
    username: root
    url: jdbc:mysql://localhost:3306/employee_management_system
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update